### PR TITLE
add functionality to clone graphs (important for unit test performance)

### PR DESCRIPTION
**Pull request by bbrehm**
I think you needed that for unit test performance in joern + codescience.

### CODE REVIEW

**Comment by bbrehm** [comment]
@mpollmeier if you want to do changes to this yourself, feel free to push on the branch and merge.

If you want me to do the changes, then add a note here and I will do (e.g. make storagepath `val` again, or factor out the code into a helper `object`).

You can also hit the merge button and change this later.

Please let me now whether this solves the unit-test performance problem!

**Comment by mpollmeier** [comment]
my changes are rather large so I'll create a follow-up PR.

**Comment by mpollmeier** [comment]
This is actually incomplete - I added a test that fails. The root cause is that `cloneThing` does not really clone anything besides `Array[GNode]` - for everything else it just returns the identity. For all primitive arrays and known things like `Array[String]` that's straightforward to implement, but what if we have property types like `java.util.Map`, or a random object?

**Comment by bbrehm** [comment]
:+1: Good find!

I made setEdgeProperty also cow.

>, but what if we have property types like java.util.Map, or a random object?

Not supported by flatgraph.

**Comment by mpollmeier** [comment]
👍🏻 thank you

**Comment by mpollmeier** [comment]
wouldn't it be better to just add this case to `cloneThing`?
i.e. 
```
        case a: Array[_] =>
          a.clone()
```

**Comment by mpollmeier** [comment]
I'd prefer https://github.com/joernio/flatgraph/pull/163
But if you prefer this variant, we can go with this as well.

**Comment by mpollmeier** [comment]
switching to https://github.com/joernio/flatgraph/pull/163

**Pull request closed without merging**
